sonar.projectName=Scaffy
sonar.sources=scaffy-be/src/main/java,scaffy-fe/src
sonar.tests=scaffy-be/src/test/java,scaffy-fe/test
sonar.test.inclusions=scaffy-be/src/test/java/**/*.java,scaffy-fe/test/**/*.test.ts,scaffy-fe/test/**/*.test.tsx
sonar.exclusions=scaffy-fe/dist/**,scaffy-fe/coverage/**,scaffy-fe/node_modules/**,scaffy-be/target/**

sonar.java.binaries=scaffy-be/target/classes
sonar.coverage.jacoco.xmlReportPaths=scaffy-be/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=scaffy-fe/coverage/lcov.info
