package com.scaffy.backend.analyze;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;

import org.junit.jupiter.api.Test;

class SecurityScanningCapabilityRuleSetTest {

	private final PipelineAnalyzer analyzer = new PipelineAnalyzer(
			new YamlPipelineParser(),
			new ProviderDetector(),
			List.of(new GitHubActionsParser(), new GitLabCiParser()),
			List.of(
					new BuildCapabilityRuleSet(),
					new TestCapabilityRuleSet(),
					new CodeAnalysisCapabilityRuleSet(),
					new SecurityScanningCapabilityRuleSet(),
					new ArtifactCapabilityRuleSet(),
					new DeploymentCapabilityRuleSet(),
					new NotificationCapabilityRuleSet()),
				new ScoringEngine());

	@Test
	void detectsGitHubCodeQlAndSarifSecurityScan() {
		AnalysisResponse response = analyzer.analyze("ci.yml", """
				name: Security
				on: [push]
				jobs:
				  security:
				    runs-on: ubuntu-latest
				    steps:
				      - uses: github/codeql-action/init@v3
				      - uses: github/codeql-action/analyze@v3
				      - uses: github/codeql-action/upload-sarif@v3
				""");

		DomainScore security = security(response);

		assertThat(response.dimensions()).extracting(DomainScore::dimension)
				.containsExactly("build_release", "testing_maturity", "workflow_quality", "security_integration", "deployment_automation");
		assertThat(security.status()).isEqualTo(AnalysisStatus.PARTIAL);
		assertThat(evidence(security)).contains("github/codeql-action/init@v3");
	}

	@Test
	void detectsDependencyScanning() {
		AnalysisResponse response = analyzer.analyze("ci.yml", """
				name: Dependencies
				on: [pull_request]
				jobs:
				  dependency-scan:
				    runs-on: ubuntu-latest
				    steps:
				      - run: npm audit --audit-level=high
				      - uses: github/dependency-review-action@v4
				""");

		DomainScore security = security(response);

		assertThat(security.status()).isEqualTo(AnalysisStatus.PARTIAL);
		assertThat(evidence(security)).contains("npm audit --audit-level=high");
	}

	@Test
	void detectsGitLabSecurityReportsAsComplete() {
		AnalysisResponse response = analyzer.analyze(".gitlab-ci.yml", """
				security_reports:
				  stage: test
				  script:
				    - echo "security reports generated by included scanners"
				  artifacts:
				    reports:
				      sast: gl-sast-report.json
				      dependency_scanning: gl-dependency-scanning-report.json
				      container_scanning: gl-container-scanning-report.json
				      secret_detection: gl-secret-detection-report.json
				""");

		DomainScore security = security(response);

		assertThat(security.status()).isNotEqualTo(AnalysisStatus.MISSING);
		assertThat(evidence(security)).contains(
				"artifacts.reports.sast",
				"artifacts.reports.dependency_scanning",
				"artifacts.reports.secret_detection",
				"artifacts.reports.container_scanning");
	}

	@Test
	void detectsSecretContainerAndIacScanning() {
		AnalysisResponse response = analyzer.analyze("ci.yml", """
				name: Security
				on: [push]
				jobs:
				  security:
				    runs-on: ubuntu-latest
				    steps:
				      - run: gitleaks detect --source .
				      - run: trivy image ghcr.io/acme/app:$GITHUB_SHA
				      - run: checkov -d infra/
				""");

		DomainScore security = security(response);

		assertThat(security.status()).isEqualTo(AnalysisStatus.PARTIAL);
		assertThat(evidence(security)).contains("gitleaks detect --source .", "trivy image ghcr.io/acme/app:$GITHUB_SHA");
	}

	@Test
	void detectsSemgrepOnlyWithSecurityContext() {
		AnalysisResponse securityResponse = analyzer.analyze("ci.yml", """
				name: Security
				on: [push]
				jobs:
				  sast:
				    runs-on: ubuntu-latest
				    steps:
				      - name: Security scan
				        run: semgrep --config p/security-audit .
				""");

		assertThat(security(securityResponse).status()).isNotEqualTo(AnalysisStatus.MISSING);
		assertThat(evidence(security(securityResponse))).contains("semgrep --config p/security-audit .");

		AnalysisResponse lintResponse = analyzer.analyze("ci.yml", """
				name: Lint
				on: [push]
				jobs:
				  lint:
				    runs-on: ubuntu-latest
				    steps:
				      - run: semgrep --config p/default .
				""");

		assertThat(security(lintResponse).status()).isEqualTo(AnalysisStatus.MISSING);
	}

	@Test
	void nonSecurityPipelinesReturnMissingSecurityStatus() {
		String[] commands = {
				"npm run build",
				"npm test",
				"npm run lint",
				"python -m build",
				"kubectl apply -f k8s/",
				"curl -X POST $SLACK_WEBHOOK_URL"
		};

		for (String command : commands) {
			AnalysisResponse response = analyzer.analyze("ci.yml", """
					name: CI
					on: [push]
					jobs:
					  ci:
					    runs-on: ubuntu-latest
					    steps:
					      - run: %s
					""".formatted(command));

			DomainScore security = security(response);

			assertThat(security.status())
					.as("Expected no security scanning detection for %s", command)
					.isEqualTo(AnalysisStatus.MISSING);
			assertThat(security.score()).isEqualTo(0.0);
		}
	}

	@Test
	void manualOnlySecurityWorkflowLosesAutomaticTriggerScore() {
		AnalysisResponse response = analyzer.analyze("ci.yml", """
				name: Manual security
				on: [workflow_dispatch]
				jobs:
				  security:
				    runs-on: ubuntu-latest
				    steps:
				      - run: npm audit
				      - run: gitleaks detect --source .
				""");

		DomainScore security = security(response);

		assertThat(security.status()).isNotEqualTo(AnalysisStatus.MISSING);
	}

	private DomainScore security(AnalysisResponse response) {
		return response.dimensions().stream()
				.filter(dimension -> "security_integration".equals(dimension.dimension()))
				.findFirst()
				.orElseThrow();
	}

	private List<String> evidence(DomainScore analysis) {
		return analysis.capabilityScores().stream()
				.flatMap(cs -> cs.findings().stream())
				.filter(f -> f.type() == FindingType.POSITIVE)
				.map(CapabilityFinding::evidence)
				.toList();
	}
}
