CREATE TABLE repository_analysis_jobs (
    id UUID PRIMARY KEY,
    workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    repository_connection_id UUID NOT NULL REFERENCES repository_connections(id) ON DELETE CASCADE,
    analysis_run_id UUID REFERENCES repository_analysis_runs(id) ON DELETE SET NULL,
    status VARCHAR(32) NOT NULL,
    progress_message TEXT,
    progress_percent INT NOT NULL DEFAULT 0,
    error_message TEXT,
    attempt_count INT NOT NULL DEFAULT 0,
    max_attempts INT NOT NULL DEFAULT 3,
    heartbeat_at TIMESTAMP WITH TIME ZONE,
    next_attempt_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX repository_analysis_jobs_repository_status_idx
    ON repository_analysis_jobs(repository_connection_id, status, created_at DESC);

CREATE INDEX repository_analysis_jobs_user_status_idx
    ON repository_analysis_jobs(user_id, status, created_at DESC);

CREATE INDEX repository_analysis_jobs_next_attempt_idx
    ON repository_analysis_jobs(status, next_attempt_at);

CREATE INDEX repository_analysis_jobs_heartbeat_idx
    ON repository_analysis_jobs(status, heartbeat_at);

CREATE TABLE repository_analysis_job_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id UUID NOT NULL REFERENCES repository_analysis_jobs(id) ON DELETE CASCADE,
    stream VARCHAR(16) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX repository_analysis_job_logs_job_created_idx
    ON repository_analysis_job_logs(job_id, created_at, id);

CREATE TABLE app_notifications (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE,
    type VARCHAR(64) NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    target_url TEXT,
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX app_notifications_user_unread_idx
    ON app_notifications(user_id, read_at, created_at DESC);
