CREATE TABLE initializer_generation_job_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id UUID NOT NULL REFERENCES initializer_generation_jobs(id) ON DELETE CASCADE,
    stream VARCHAR(16) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX initializer_generation_job_logs_job_created_idx
    ON initializer_generation_job_logs(job_id, created_at, id);
