ALTER TABLE initializer_generation_jobs
    ADD COLUMN user_id UUID REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX initializer_generation_jobs_user_id_idx
    ON initializer_generation_jobs(user_id);

CREATE TABLE repository_publication_jobs (
    id UUID PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    initializer_generation_job_id UUID NOT NULL REFERENCES initializer_generation_jobs(id) ON DELETE CASCADE,
    provider VARCHAR(32) NOT NULL,
    repository_name VARCHAR(100) NOT NULL,
    repository_description TEXT,
    visibility VARCHAR(16) NOT NULL,
    status VARCHAR(32) NOT NULL,
    progress_message TEXT,
    error_message TEXT,
    repository_owner VARCHAR(255),
    repository_url TEXT,
    repository_connection_id UUID REFERENCES repository_connections(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX repository_publication_jobs_user_created_idx
    ON repository_publication_jobs(user_id, created_at DESC);

CREATE INDEX repository_publication_jobs_status_created_idx
    ON repository_publication_jobs(status, created_at);

CREATE TABLE repository_publication_job_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id UUID NOT NULL REFERENCES repository_publication_jobs(id) ON DELETE CASCADE,
    stream VARCHAR(16) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX repository_publication_job_logs_job_created_idx
    ON repository_publication_job_logs(job_id, created_at, id);
