FROM node:24-alpine AS build
WORKDIR /workspace
COPY package*.json ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /workspace/dist/{{projectName}}/browser /usr/share/nginx/html
EXPOSE 80
