FROM node:22-alpine AS build
WORKDIR /workspace
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /workspace/dist/{{projectName}}/browser /usr/share/nginx/html
EXPOSE 80
